# Meilisearch Configuration File
# This file configures Meilisearch for the RAG system

[env]
# Environment: development, production
env = "development"

# Master key for authentication (required in production)
# master_key = "your_master_key_here"

# Database path
db_path = "/meili_data"

# HTTP server configuration
[server]
# Address to bind the HTTP server
http_addr = "0.0.0.0:7700"

# Payload size limit
http_payload_size_limit = "100MB"

# CORS configuration
[cors]
# Allow all origins in development
allowed_origins = ["*"]

# Logging configuration
[log]
# Log level: ERROR, WARN, INFO, DEBUG, TRACE
level = "INFO"

# Performance configuration
[experimental]
# Maximum memory for indexing operations
max_indexing_memory = "2GB"

# Maximum number of indexing threads
max_indexing_threads = 4

# Vector search configuration
[vector]
# Default vector dimensions (EmbeddingGemma: 768, MRL: 256-512)
default_dimension = 768

# Default distance metric: cosine, dot, euclidean
default_distance_metric = "cosine"

# Index configuration
[index]
# Default index name for RAG documents
default_name = "rag_documents"

# Maximum documents per batch
max_documents_per_batch = 1000

# Backup configuration
[backup]
# Snapshot directory
snapshot_dir = "/meili_data/snapshots"

# Snapshot interval
snapshot_interval = "24h"
